#pragma once
#include "fable/FCore.h"
#include "fable/MainGameComponent.h"
#include "fable/World.h"
#include "fable/PlayerManager.h"
#include "fable/Player.h"
#include "fable/Pointer.h"
#include "fable/GameCamera.h"
#include "fable/QuestManager.h"